In [2]:
import numpy as np 

arr = np.array([1,2,3,22,4,3,6,1,7,9,8,3,19,5,6])

np.unique(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 19, 22])

In [8]:
# Where is the max value

print(np.argmax(arr))

np.argmin(arr)

3


np.int64(0)

In [13]:
# Where provide you index of elelments

np.where(arr>4)

(array([ 3,  6,  8,  9, 10, 12, 13]),)

In [7]:
np.histogram(arr,bins=[0,10,20,30])

(array([13,  1,  1]), array([ 0, 10, 20, 30]))

In [29]:
# Replace values with 0
arr = np.where(arr>4,0,arr)

In [30]:
arr

array([1, 2, 0, 0, 4, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])