In [1]:
import numpy as np

arr = np.arange(2,23,3)

print(arr)

[ 2  5  8 11 14 17 20]


In [2]:
import numpy as np

arr = np.arange(1,13).reshape(6,2)

print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [3]:
import numpy as np

arr = np.arange(1,13).reshape(3,4)

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
