In [1]:
import numpy as np

arr = np.ones((4,5))

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np

arr = np.zeros((4,5))

print(arr)

In [8]:
import numpy as np
import random

arr = np.random.random((2,3))

print(arr)

[[0.51635416 0.62387472 0.97003222]
 [0.96050021 0.65181732 0.14228449]]


In [12]:
import numpy as np

arr = np.eye(2,3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]]


In [15]:
import numpy as np

arr = np.identity(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
import numpy as np

arr = np.linspace(2,3,4)

print(arr)

[2.         2.33333333 2.66666667 3.        ]
