In [1]:
print("hellow world")

hellow world


In [2]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [3]:
import numpy as np

arr  = np.arange(1,6)**2

print(arr)

[ 1  4  9 16 25]


In [10]:
import numpy as np 

arr = np.array([[1,2,3,4,5,6],[2,8,4,6,7,3]])

print(arr)

print("Dimension Of Array : ",arr.ndim)

[[1 2 3 4 5 6]
 [2 8 4 6 7 3]]
Dimension Of Array :  2
