In [10]:
import numpy as np

arr = np.arange(12).reshape(3,4)

arr2 = np.arange(12,24).reshape(3,4)

print(arr+arr2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [11]:
import numpy as np

arr = np.arange(12).reshape(3,4)

arr2 = np.arange(12,24).reshape(3,4)

print(arr*arr2)

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


In [16]:
import numpy as np 

arr = np.arange(42,84,2)

print(arr + 2)

[44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84]


In [21]:
import numpy as np 

arr = np.arange(40).reshape(8,5)



print(arr>=15)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
