In [12]:
import numpy as np

arr = np.arange(27).reshape(3,3,3)

print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [20]:
import numpy as np

arr = np.arange(27).reshape(3,3,3)

print(arr[::2,0,::2])

[[ 0  2]
 [18 20]]


In [16]:
import numpy as np

arr = np.arange(27).reshape(3,3,3)

print(arr[2,1:,1:])

[[22 23]
 [25 26]]


In [15]:
import numpy as np

arr = np.arange(27).reshape(3,3,3)

print(arr[0,1,:])

[3 4 5]


In [ ]:
import numpy as np

arr = np.arange(27).reshape(3,3,3)

print(arr[::2])

In [10]:
import numpy as np

arr = np.arange(12).reshape(3,4)

print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
import numpy as np

arr = np.arange(12).reshape(3,4)

print(arr[0:2,1:4])

[[1 2 3]
 [5 6 7]]


In [7]:
import numpy as np

arr = np.arange(12).reshape(3,4)

print(arr[::2,1::2])

[[ 1  3]
 [ 9 11]]


In [8]:
import numpy as np

arr = np.arange(12).reshape(3,4)

print(arr[::2,::3])

[[ 0  3]
 [ 8 11]]
